# Generated by Django 5.1.3 on 2024-11-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('Digital Marketing', 'Digital Marketing'), ('Web Development', 'Web Development'), ('Graphic Designing', 'Graphic Designing'), ('Social Media', 'Social Media')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
