# Generated by Django 5.1.3 on 2025-02-20 10:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_taskhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_encoding',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('Graphic Designing', 'Graphic Designing'), ('Social Media', 'Social Media'), ('Digital Marketing', 'Digital Marketing'), ('Video Editing', 'Video Editing'), ('Web Development', 'Web Development'), ('Videography', 'Videography'), ('Photography', 'Photography'), ('Management', 'Management'), ('Content Writing', 'Content Writing')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('punch_in_time', models.DateTimeField(blank=True, null=True)),
                ('punch_in_location', models.CharField(blank=True, max_length=255, null=True)),
                ('punch_out_time', models.DateTimeField(blank=True, null=True)),
                ('punch_out_location', models.CharField(blank=True, max_length=255, null=True)),
                ('work_type', models.CharField(blank=True, choices=[('WFO', 'Work from Office'), ('WFH', 'Work from Home')], max_length=20, null=True)),
                ('face_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('On Time', 'On Time'), ('Punched in Late', 'Punched in Late'), ('Punched out Early', 'Punched out Early'), ('Absent', 'Absent')], default='Absent', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(default='Absent without Punch-in', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
