# Generated by Django 5.1.3 on 2025-02-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_face_encoding_faceencoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='reason',
            field=models.CharField(blank=True, help_text='Reason for Work from Home, if applicable', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status_punchin',
            field=models.CharField(choices=[('On Time', 'On Time'), ('Late', 'Late'), ('Absent', 'Absent')], default='Absent', help_text='Status specifically for punch-in', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status_punchout',
            field=models.CharField(choices=[('On Time', 'On Time'), ('Early', 'Early'), ('Absent', 'Absent')], default='Absent', help_text='Status specifically for punch-out', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('On Time', 'On Time'), ('Punched in Late', 'Punched in Late'), ('Punched out Early', 'Punched out Early'), ('Absent', 'Absent')], default='Absent', help_text='Overall attendance status', max_length=20),
        ),
    ]
