# Generated by Django 5.1.3 on 2025-02-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_attendance_reason_attendance_status_punchin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Lose of Pay', 'Lose of Pay'), ('Casual Leave', 'Casual Leave'), ('Paid Leave', 'Paid Leave'), ('Sick Leave', 'Sick Leave')], default='Lose of Pay', max_length=20),
        ),
    ]
