# Generated by Django 5.1.3 on 2024-11-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project_projectimage_projectmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='department',
            field=models.CharField(blank=True, choices=[('Digital Marketing', 'Digital Marketing'), ('Web Development', 'Web Development'), ('Graphic Designing', 'Graphic Designing'), ('Social Media', 'Social Media')], max_length=50, null=True),
        ),
    ]
