# Generated by Django 5.1.3 on 2025-02-27 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_holiday_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='leave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.leave'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task', 'Task'), ('project', 'Project'), ('leave', 'Leave')], max_length=10),
        ),
    ]
