# Generated by Django 5.1.3 on 2025-02-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_notification_leave_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='half_day_option',
            field=models.CharField(blank=True, choices=[('', 'Full Day'), ('First Half', 'First Half'), ('Second Half', 'Second Half')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Full Day - Lose of Pay', 'Full Day - Lose of Pay'), ('Full Day - Casual Leave', 'Full Day - Casual Leave'), ('Full Day - Paid Leave', 'Full Day - Paid Leave'), ('Full Day - Sick Leave', 'Full Day - Sick Leave'), ('Half Day - First Half - Lose of Pay', 'Half Day - First Half - Lose of Pay'), ('Half Day - Second Half - Lose of Pay', 'Half Day - Second Half - Lose of Pay'), ('Half Day - First Half - Casual Leave', 'Half Day - First Half - Casual Leave'), ('Half Day - Second Half - Casual Leave', 'Half Day - Second Half - Casual Leave'), ('Half Day - First Half - Paid Leave', 'Half Day - First Half - Paid Leave'), ('Half Day - Second Half - Paid Leave', 'Half Day - Second Half - Paid Leave'), ('Half Day - First Half - Sick Leave', 'Half Day - First Half - Sick Leave'), ('Half Day - Second Half - Sick Leave', 'Half Day - Second Half - Sick Leave')], default='Full Day - Lose of Pay', max_length=50),
        ),
    ]
